services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=maya         # THIS IS TO BE REPLACED
      - DOCKER_INFLUXDB_INIT_PASSWORD=Huniee16        # THIS IS TO BE REPLACED
      - DOCKER_INFLUXDB_INIT_ORG=my-org                   # THIS CAN BE CHANGED
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf              # THIS CAN BE CHANGED
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ksdkdsjfhkhfakhskhdeiri   # THIS IS TO BE REPLACED

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=maya
      - GF_SECURITY_ADMIN_PASSWORD=Huniee16
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:

